projects:
- slug: argoproj/argo-cd
  tier: Graduated
  rss: null
- slug: cert-manager/cert-manager
  tier: Graduated
  rss: null
- slug: cilium/cilium
  tier: Graduated
  rss: https://cilium.io/blog/rss.xml
- slug: cloudevents/spec
  tier: Graduated
  rss: https://cloudevents.io/index.xml
- slug: containerd/containerd
  tier: Graduated
  rss: https://containerd.io/index.xml
- slug: coredns/coredns
  tier: Graduated
  rss: https://coredns.io/index.xml
- slug: cri-o/cri-o
  tier: Graduated
  rss: null
- slug: cubeFS/cubefs
  tier: Graduated
  rss: https://cubefs.io/feed.xml
- slug: dapr/dapr
  tier: Graduated
  rss: https://dapr.io/index.xml
- slug: envoyproxy/envoy
  tier: Graduated
  rss: null
- slug: etcd-io/etcd
  tier: Graduated
  rss: https://etcd.io/index.xml
- slug: falcosecurity/falco
  tier: Graduated
  rss: https://falco.org/feed.xml
- slug: fluent/fluentd
  tier: Graduated
  rss: null
- slug: fluxcd/flux2
  tier: Graduated
  rss: https://fluxcd.io/blog/index.xml
- slug: goharbor/harbor
  tier: Graduated
  rss: https://goharbor.io/blog/index.xml
- slug: helm/helm
  tier: Graduated
  rss: https://helm.sh/index.xml
- slug: in-toto/in-toto
  tier: Graduated
  rss: https://in-toto.io/blog/index.xml
- slug: istio/istio
  tier: Graduated
  rss: https://istio.io/feed.xml
- slug: jaegertracing/jaeger
  tier: Graduated
  rss: null
- slug: kedacore/keda
  tier: Graduated
  rss: https://keda.sh/index.xml
- slug: kubeedge/kubeedge
  tier: Graduated
  rss: https://kubeedge.io/en/blog/rss.xml
- slug: kubernetes/kubernetes
  tier: Graduated
  rss: https://kubernetes.io/feed.xml
- slug: linkerd/linkerd2
  tier: Graduated
  rss: null
- slug: open-policy-agent/opa
  tier: Graduated
  rss: null
- slug: prometheus/prometheus
  tier: Graduated
  rss: null
- slug: rook/rook
  tier: Graduated
  rss: null
- slug: spiffe/spiffe
  tier: Graduated
  rss: https://spiffe.io/index.xml
- slug: spiffe/spire
  tier: Graduated
  rss: null
- slug: theupdateframework/python-tuf
  tier: Graduated
  rss: null
- slug: tikv/tikv
  tier: Graduated
  rss: https://tikv.org/blog/index.xml
- slug: vitessio/vitess
  tier: Graduated
  rss: https://vitess.io/index.xml
