name: Build & Deploy CNCF Newsletter (React + Python Best Practices) to Pages

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---------- Python (lint + build items.json) ----------
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt black ruff mypy

      - name: Lint & type check
        run: |
          black --check .
          ruff check .
          mypy .

      - name: Build items.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py --since '3 days' --out ./build
          test -f build/items.json

      # ---------- React ----------
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build React app
        working-directory: ./web
        run: |
          npm ci || npm i
          npm run build

      # ---------- Stage Pages site ----------
      - name: Prepare Pages site
        run: |
          set -euo pipefail
          DATE="$(date -u +%F)"
          mkdir -p site
          echo "cncfnews.org" > site/CNAME
          touch site/.nojekyll

          mkdir -p "site/${DATE}"
          cp -r web/dist/* "site/${DATE}/"
          cp build/items.json "site/${DATE}/items.json"
          cp "site/${DATE}/index.html" "site/${DATE}/404.html"

          cp -r web/dist/* site/
          cp build/items.json site/items.json
          cp site/index.html site/404.html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
