name: Build & Deploy CNCF Newsletter to Pages

on:
  schedule:
    - cron: '0 3 * * *'   # daily 03:00 UTC (~08:30 IST)
  workflow_dispatch:

permissions:
  contents: read
  pages: write        # required for deploy
  id-token: write     # required for OIDC

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Sync CNCF Graduated projects
        run: |
          source .venv/bin/activate
          python tools/sync_projects.py

      - name: Build issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}         # optional
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }} # optional (email)
        run: |
          source .venv/bin/activate
          # Build WITHOUT email send; we want static files only
          python main.py --since '3 days' --out ./build

      - name: Prepare Pages site
        run: |
          set -euo pipefail
          DATE="$(date -u +%F)"
          mkdir -p site/.well-known
          echo "cncfnews.org" > site/CNAME
          touch site/.nojekyll

          # Make latest available at / (root)
          cp build/issue.html site/index.html
          cp build/items.json site/items.json
          cp build/about.html  "site/about.html"

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
